### PR TITLE
Add support for RN 0.71.0

### LINKED ISSUE #3: [RN 0.71.0 build error] Expected directory '.../node_modules/react-native/android' to contain exactly one file, however, it contains no files
Hey there, thanks a lot for all the work on this 🙏 

I came across the following when I updated a project to 0.71.0 when building android:
```
* Where:
Build file '.../node_modules/react-native-random-values-jsi-helper/android/build.gradle' line: 172

* What went wrong:
A problem occurred evaluating project ':react-native-random-values-jsi-helper'.
> Expected directory '.../node_modules/react-native/android' to contain exactly one file, however, it contains no files.
```

seems to be related to https://github.com/react-native-community/discussions-and-proposals/pull/508

also, they added this to react-native/android/README.md

Screenshot 2023-01-19 at 05 49 33

I tried to fix it, but then came across another issue related to CMakeLists.txt, 
`[CMake Error: The following variables are used in this project, but they are set to NOTFOUND]` for REACT_NATIVE_JNI_LIB and JSI_LIB

probably was trying the wrong thing. 😄

### PR DESCRIPTION
**Pull request by mmmoussa**
This PR is based on https://github.com/mrousavy/react-native-mmkv/pull/480 and https://github.com/mrousavy/react-native-mmkv/pull/499. Tested it in my own app and confirmed it's working. Closes #3.

### CODE REVIEW

**Comment by jahglow** [comment]
@mateioprea please merge this PR ASAP

**Comment by mateioprea** [comment]
Hi @mmmoussa and @jahglow. I've been away for the past week. Let me review this quickly and merge it.

**Comment by mateioprea** [comment]
Sorry, but your PR doesn't work on older versions of RN. You can test it with the example app. Do you want to fix these issues?

**Comment by jahglow** [comment]
> 't work on older versions of RN. You can test it with the example app.

@mmmoussa ?

**Comment by jahglow** [comment]
@mateioprea I'm not good at native code, maybe major upgrade will do the thing and have a division for pre 0.71 react and post? That's what is usually done to resolve backward incompatibility especially there were no changes to the lib for a year.

**Comment by a-eid** [comment]
@mateioprea 

> Sorry, but your PR doesn't work on older versions of RN. You can test it with the example app. Do you want to fix these issues?

I don't believe it's trivial to support 71 as well as prior RN versions, as most libs do you should note in the readme which versions support which RN version. 


~does this PR fixes this error ?~
yes.

Screenshot 2023-02-25 at 13 56 27

~I tried patching the package but it doesn't seem to be working.~
patching the package worked.

**Comment by hirbod** [comment]
I can confirm that a lot of libs that support RN 71 have dropped support for older versions. I'd bump the major version and drop a deprecation warning. Users can still use a lower version when they need support for < 0.71 imho.

**Comment by a-eid** [comment]
@hirbod exactly.

**Comment by mateioprea** [comment]
> I can confirm that a lot of libs that support RN 71 have dropped support for older versions. I'd bump the major version and drop a deprecation warning. Users can still use a lower version when they need support for < 0.71 imho.

@hirbod and that means that unless I’m using new arch, I won’t be able to get latest updates?

**Comment by hirbod** [comment]
No, @mateioprea, when you follow the PR like done in react-native-mmkv, or this open PR (which does base on the mmkv one) https://github.com/mrousavy/react-native-blob-jsi-helper/pull/11 - your library will still work on Paper, but it requires RN 0.71.

The template and the build steps got much better and faster with 0.71 and supporting older versions is just tedious work.

**Comment by mateioprea** [comment]
Sorry, but this doesn't work for me. I get this error: ` java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so caused by: dlopen failed: cannot locate symbol` 

I don't know if its me or the new implementation, but i won't release this until i can run it successfully.

**Comment by mateioprea** [comment]
Found the issue. I'm gonna release this later today.

**Comment by mateioprea** [comment]
@mmmoussa @jahglow released under v2.0.0: https://www.npmjs.com/package/react-native-random-values-jsi-helper. 

Thank you for your contributions! 🥇

**Pull request merged**
